
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn unicode_operator_definitions() {
  read_and_parse::test("testdata/unicode/operators-unicode.tla", "Unicode Operator Definitions");
}


#[test]
fn unicode_operator_declarations_as_parameters() {
  read_and_parse::test("testdata/unicode/operators-unicode.tla", "Unicode Operator Declarations as Parameters");
}


#[test]
fn unicode_operator_application() {
  read_and_parse::test("testdata/unicode/operators-unicode.tla", "Unicode Operator Application");
}


#[test]
fn unicode_operator_references() {
  read_and_parse::test("testdata/unicode/operators-unicode.tla", "Unicode Operator References");
}


#[test]
fn nonfix_unicode_operators() {
  read_and_parse::test("testdata/unicode/operators-unicode.tla", "Nonfix Unicode Operators");
}

