
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn bounded_quantification() {
  read_and_parse::test("testdata/unicode/quantification-unicode.tla", "Bounded Quantification");
}


#[test]
fn unbounded_quantification() {
  read_and_parse::test("testdata/unicode/quantification-unicode.tla", "Unbounded Quantification");
}


#[test]
fn bounded_choose() {
  read_and_parse::test("testdata/unicode/quantification-unicode.tla", "Bounded CHOOSE");
}


#[test]
fn unbounded_choose() {
  read_and_parse::test("testdata/unicode/quantification-unicode.tla", "Unbounded CHOOSE");
}

