[package]
name = "tlc-rs"
version = "0.0.1"
edition = "2021"
authors = ["Ben Eggers <ben@beneggers.com>"]

[workspace]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
lib = { path = "lib" }
