
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn pluscal_comments() {
  read_and_parse::test("testdata/pluscal/comments.tla", "PlusCal Comments");
}

#[test]
fn pluscal_fair_algorithm() {
  read_and_parse::test("testdata/pluscal/comments.tla", "PlusCal Fair Algorithm");
}
