
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn comment_in_conjlist() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Comment in Conjlist");
}

#[test]
fn comment_in_disjlist() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Comment in Disjlist");
}

#[test]
fn block_comment_in_conjlist() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Block Comment in Conjlist");
}

#[test]
fn block_comment_in_disjlist() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Block Comment in Disjlist");
}

#[test]
fn block_comment_in_disjlist() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Block Comment in Disjlist");
}

#[test]
fn block_comment_preceding_jlist_bullet() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Block Comment Preceding Jlist Bullet");
}

#[test]
fn block_comment_preceding_jlist_bullet_from_previous_line() {
  read_and_parse::test("testdata/exclude/sany/comment-jlist.tla", "Block Comment Preceding Jlist Bullet From Previous Line");
}
