
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn string_with_comment_start() {
  read_and_parse::test("testdata/exclude/sany/string.tla", "String with comment start");
}
