// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn basic_assumeprove() {
    read_and_parse::test("testdata/assume-prove.tla", "Basic AssumeProve");
}

#[test]
fn nested_assumeprove_with_label() {
    read_and_parse::test("testdata/assume-prove.tla", "Nested AssumeProve With Label");
}

#[test]
fn assumeprove_with_new_constant() {
    read_and_parse::test("testdata/assume-prove.tla", "AssumeProve With New Constant");
}

#[test]
fn assumeprove_with_new_operator() {
    read_and_parse::test("testdata/assume-prove.tla", "AssumeProve With New Operator");
}

#[test]
fn assumeprove_in_suffices_step() {
    read_and_parse::test("testdata/assume-prove.tla", "AssumeProve in Suffices Step");
}

#[test]
fn assumeprove_with_mixed_assumptions() {
    read_and_parse::test(
        "testdata/assume-prove.tla",
        "AssumeProve with Mixed Assumptions",
    );
}
