
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn basic_case() {
  read_and_parse::test("testdata/case.tla", "Basic CASE");
}

#[test]
fn solitary_case() {
  read_and_parse::test("testdata/case.tla", "Solitary CASE");
}

#[test]
fn case_with_dangling_else() {
  read_and_parse::test("testdata/case.tla", "CASE with dangling else");
}

#[test]
fn conjlist_with_case() {
  read_and_parse::test("testdata/case.tla", "Conjlist with CASE");
}

#[test]
fn conjlist_inside_case() {
  read_and_parse::test("testdata/case.tla", "Conjlist inside CASE");
}

#[test]
fn disjlist_with_case() {
  read_and_parse::test("testdata/case.tla", "Disjlist with CASE");
}

#[test]
fn disjlist_inside_case() {
  read_and_parse::test("testdata/case.tla", "Disjlist inside CASE");
}
