// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn conjunct_inside_ambiguous_case_gh487() {
    read_and_parse::test(
        "testdata/exclude/sany/case.tla",
        "Conjunct Inside Ambiguous Case GH487",
    );
}

#[test]
fn unicode_conjunct_inside_ambiguous_case_gh487() {
    read_and_parse::test(
        "testdata/exclude/sany/case.tla",
        "Unicode Conjunct Inside Ambiguous Case GH487",
    );
}
