// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn recursive_inside_letin() {
    read_and_parse::test("testdata/let_in.tla", "RECURSIVE inside LETIN");
}

#[test]
fn conjlist_with_letin() {
    read_and_parse::test("testdata/let_in.tla", "Conjlist with LETIN");
}

#[test]
fn conjlist_with_recursive_in_letin() {
    read_and_parse::test("testdata/let_in.tla", "Conjlist with RECURSIVE in LETIN");
}

#[test]
fn conjlist_with_instance_in_letin() {
    read_and_parse::test("testdata/let_in.tla", "Conjlist with INSTANCE in LETIN");
}

#[test]
fn conjlist_inside_letin() {
    read_and_parse::test("testdata/let_in.tla", "Conjlist inside LETIN");
}

#[test]
fn disjlist_with_letin() {
    read_and_parse::test("testdata/let_in.tla", "Disjlist with LETIN");
}

#[test]
fn disjlist_with_recursive_in_letin() {
    read_and_parse::test("testdata/let_in.tla", "Disjlist with RECURSIVE in LETIN");
}

#[test]
fn disjlist_with_instance_in_letin() {
    read_and_parse::test("testdata/let_in.tla", "Disjlist with INSTANCE in LETIN");
}

#[test]
fn disjlist_inside_letin() {
    read_and_parse::test("testdata/let_in.tla", "Disjlist inside LETIN");
}
