// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn single_module() {
    read_and_parse::test("testdata/modules.tla", "Single module");
}

#[test]
fn single_module_with_lines() {
    read_and_parse::test("testdata/modules.tla", "Single module with lines");
}

#[test]
fn module_with_extends() {
    read_and_parse::test("testdata/modules.tla", "Module with EXTENDS");
}

#[test]
fn nested_modules() {
    read_and_parse::test("testdata/modules.tla", "Nested modules");
}

#[test]
fn multiple_nested_modules() {
    read_and_parse::test("testdata/modules.tla", "Multiple Nested modules");
}
