// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn all_number_formats() {
    read_and_parse::test("testdata/number.tla", "All Number Formats");
}

#[test]
fn all_number_sets() {
    read_and_parse::test("testdata/number.tla", "All Number Sets");
}
