
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn minus_and_negative() {
  read_and_parse::test("testdata/operators.tla", "Minus and Negative");
}


#[test]
fn lambda_parameter() {
  read_and_parse::test("testdata/operators.tla", "LAMBDA Parameter");
}

