// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn lexicallyconflicting_nonfix_operators() {
    read_and_parse::test(
        "testdata/operators.tla",
        "LexicallyConflicting Nonfix Operators",
    );
}

#[test]
fn minus_and_negative() {
    read_and_parse::test("testdata/operators.tla", "Minus and Negative");
}

#[test]
fn higherorder_operator_parameter_declarations() {
    read_and_parse::test(
        "testdata/operators.tla",
        "HigherOrder Operator Parameter Declarations",
    );
}

#[test]
fn lambda_parameter() {
    read_and_parse::test("testdata/operators.tla", "LAMBDA Parameter");
}
