// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_while() {
    read_and_parse::test("testdata/pluscal/while.tla", "PlusCal PSyntax While");
}

#[test]
fn pluscal_csyntax_while() {
    read_and_parse::test("testdata/pluscal/while.tla", "PlusCal CSyntax While");
}
