// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_if() {
    read_and_parse::test("testdata/pluscal/if.tla", "PlusCal PSyntax If");
}

#[test]
fn pluscal_csyntax_if() {
    read_and_parse::test("testdata/pluscal/if.tla", "PlusCal CSyntax If");
}
