// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_macros() {
    read_and_parse::test("testdata/pluscal/macros.tla", "PlusCal PSyntax Macros");
}

#[test]
fn pluscal_csyntax_macros() {
    read_and_parse::test("testdata/pluscal/macros.tla", "PlusCal CSyntax Macros");
}
