// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_processes() {
    read_and_parse::test(
        "testdata/pluscal/processes.tla",
        "PlusCal PSyntax Processes",
    );
}

#[test]
fn pluscal_csyntax_processes() {
    read_and_parse::test(
        "testdata/pluscal/processes.tla",
        "PlusCal CSyntax Processes",
    );
}
