// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_block_after_conjlist() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "PlusCal Block After Conjlist",
    );
}

#[test]
fn pluscal_block_inside_conjlist() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "PlusCal Block Inside Conjlist",
    );
}

#[test]
fn pluscal_block_containing_conjlist_after_conjlist() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "PlusCal Block Containing Conjlist After Conjlist",
    );
}

#[test]
fn pluscal_block_containing_conjlist_inside_conjlist() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "PlusCal Block Containing Conjlist Inside Conjlist",
    );
}

#[test]
fn multiple_nested_pluscal_blocks() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "Multiple Nested PlusCal Blocks",
    );
}

#[test]
fn multiple_pluscal_blocks_inside_block_comment() {
    read_and_parse::test(
        "testdata/pluscal/jlist-p-syntax.tla",
        "Multiple PlusCal Blocks Inside Block Comment",
    );
}
