// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_definitions() {
    read_and_parse::test(
        "testdata/pluscal/definitions.tla",
        "PlusCal PSyntax Definitions",
    );
}

#[test]
fn pluscal_csyntax_definitions() {
    read_and_parse::test(
        "testdata/pluscal/definitions.tla",
        "PlusCal CSyntax Definitions",
    );
}
