// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn pluscal_psyntax_either() {
    read_and_parse::test("testdata/pluscal/either.tla", "PlusCal PSyntax Either");
}

#[test]
fn pluscal_csyntax_either() {
    read_and_parse::test("testdata/pluscal/either.tla", "PlusCal CSyntax Either");
}
