
// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;


#[test]
fn step_expression_or_stuttering() {
  read_and_parse::test("testdata/step_expressions.tla", "Step Expression Or Stuttering");
}


#[test]
fn step_expression_no_stuttering() {
  read_and_parse::test("testdata/step_expressions.tla", "Step Expression No Stuttering");
}


#[test]
fn step_expressions_with_jlist() {
  read_and_parse::test("testdata/step_expressions.tla", "Step Expressions with Jlist");
}

