// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn function_definition() {
    read_and_parse::test(
        "testdata/unicode/functions-unicode.tla",
        "Function Definition",
    );
}

#[test]
fn jlist_inside_function_evaluation() {
    read_and_parse::test(
        "testdata/unicode/functions-unicode.tla",
        "Jlist Inside Function Evaluation",
    );
}

#[test]
fn function_literal() {
    read_and_parse::test("testdata/unicode/functions-unicode.tla", "Function Literal");
}

#[test]
fn function_literal_with_multiple_parameters_and_jlist() {
    read_and_parse::test(
        "testdata/unicode/functions-unicode.tla",
        "Function Literal with Multiple Parameters and Jlist",
    );
}

#[test]
fn jlist_inside_unicode_function_evaluation() {
    read_and_parse::test(
        "testdata/unicode/functions-unicode.tla",
        "Jlist Inside Unicode Function Evaluation",
    );
}

#[test]
fn jlist_inside_unicode_function_set() {
    read_and_parse::test(
        "testdata/unicode/functions-unicode.tla",
        "Jlist Inside Unicode Function Set",
    );
}
