// This file was generated by scripts/gen_parser_tests.py
// Do not edit this file directly.

mod read_and_parse;

#[test]
fn use_hide_declarations() {
    read_and_parse::test("testdata/use_or_hide.tla", "Use  Hide Declarations");
}
